"""Independent reference for validation/cases.json.

Only the Python standard library (math, cmath, json) plus numpy are used; nothing is shared with
the JavaScript implementation except the expression *tree* each case was rendered from.

  arithmetic : evaluated directly with Python's math module (same operator semantics, different
               parser and libm).
  derivative : complex-step differentiation, f'(x) ~ Im f(x + ih) / h with h = 1e-30. There is no
               subtractive cancellation, so it is accurate to machine precision.
  integral   : 64-point Gauss-Legendre quadrature on [lo, hi].

Usage:  python validation/reference.py [--min-pass 0.99]
Writes validation/REPORT.md and exits non-zero if any category falls below --min-pass.
"""
import argparse
import cmath
import json
import math
import os
import statistics
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
INF = math.inf


# ------------------------------------------------------------------ real-valued environments
def _pow_lenient(a, b):
    """IEEE-style like JavaScript Math.pow: overflow/division by zero give +-inf, complex -> error."""
    try:
        r = a ** b
    except ZeroDivisionError:
        neg_odd = math.copysign(1.0, a) < 0 and float(b).is_integer() and int(b) % 2 == 1
        return -INF if neg_odd else INF
    except OverflowError:
        neg_odd = a < 0 and float(b).is_integer() and int(b) % 2 == 1
        return -INF if neg_odd else INF
    if isinstance(r, complex):
        raise ValueError("complex result")
    return r


def _exp_lenient(v):
    try:
        return math.exp(v)
    except OverflowError:
        return INF


class IllConditioned(Exception):
    """Result depends on bits below double precision; excluded from the pass rate and reported."""


def _fmod_checked(a, b):
    if b != 0 and abs(a / b) > 1e9:
        raise IllConditioned()
    return math.fmod(a, b)


def _fact(v):
    if v < 0 or int(v) != v:
        raise ValueError("factorial domain")
    return float(math.factorial(int(v)))


def calc_env(deg):
    """Mirrors the documented behaviour of the calculator (DEG or RAD)."""
    r = math.radians if deg else (lambda v: v)
    d = math.degrees if deg else (lambda v: v)

    def tan(v):
        if deg and abs(math.fmod(v, 180.0)) == 90.0:
            raise ValueError("tan undefined")
        return math.tan(r(v))

    return {
        "PI": math.pi, "E": math.e,
        "SIN": lambda v: math.sin(r(v)), "COS": lambda v: math.cos(r(v)), "TAN": tan,
        "ASIN": lambda v: d(math.asin(v)), "ACOS": lambda v: d(math.acos(v)), "ATAN": lambda v: d(math.atan(v)),
        "LN": math.log, "LOG": math.log10, "SQRT": math.sqrt, "CBRT": math.cbrt, "ABS": abs,
        "EXP": _exp_lenient, "POW": _pow_lenient, "FACT": _fact, "FMOD": _fmod_checked,
    }


def strict_env():
    """Real-valued, radians, raises on any domain problem; used to decide where f(x) is defined."""
    def pow_strict(a, b):
        r = a ** b
        if isinstance(r, complex):
            raise ValueError("complex result")
        return r
    return {
        "PI": math.pi, "E": math.e, "SIN": math.sin, "COS": math.cos, "TAN": math.tan,
        "ASIN": math.asin, "ACOS": math.acos, "ATAN": math.atan, "LN": math.log, "SQRT": math.sqrt,
        "EXP": math.exp, "POW": pow_strict,
    }


def complex_env():
    return {
        "PI": math.pi, "E": math.e, "SIN": cmath.sin, "COS": cmath.cos, "TAN": cmath.tan,
        "ASIN": cmath.asin, "ACOS": cmath.acos, "ATAN": cmath.atan, "LN": cmath.log,
        "SQRT": cmath.sqrt, "EXP": cmath.exp, "POW": lambda a, b: a ** b,
    }


def evaluate(expr, env, x=None):
    scope = dict(env)
    if x is not None:
        scope["x"] = x
    return eval(expr, {"__builtins__": {}}, scope)  # expr is generated by our own script


def close(a, b, tol):
    return abs(a - b) <= tol * max(1.0, abs(b))


def wilson(passed, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = passed / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


# ------------------------------------------------------------------ 1. arithmetic
def check_arithmetic(cases):
    envs = {True: calc_env(True), False: calc_env(False)}
    res = {"n": 0, "pass": 0, "both_error": 0, "excluded": 0, "rel_errors": [], "fail": [], "by_mode": {"DEG": [0, 0], "RAD": [0, 0]},
           "by_style": {"minimal parentheses": [0, 0], "full parentheses": [0, 0]}}
    for c in cases:
        try:
            ref = evaluate(c["py"], envs[c["deg"]])
            if isinstance(ref, complex) or not math.isfinite(ref):
                ref = None
        except IllConditioned:
            res["excluded"] += 1
            continue
        except (ValueError, ZeroDivisionError, OverflowError):
            ref = None
        ours = None if c["ours"] is None else float(c["ours"])
        res["n"] += 1
        mode = "DEG" if c["deg"] else "RAD"
        style = "minimal parentheses" if c["minimal"] else "full parentheses"
        ok = False
        if ref is None and ours is None:
            ok = True
            res["both_error"] += 1
        elif ref is not None and ours is not None and close(ours, ref, 1e-9):
            ok = True
            res["rel_errors"].append(abs(ours - ref) / max(1.0, abs(ref)))
        kind = c.get("kind", "random trees")
        res["by_mode"][mode][1] += 1
        res["by_style"][style][1] += 1
        res.setdefault("by_kind", {}).setdefault(kind, [0, 0])[1] += 1
        if ok:
            res["pass"] += 1
            res["by_mode"][mode][0] += 1
            res["by_style"][style][0] += 1
            res["by_kind"][kind][0] += 1
        else:
            kind = ("ours errors, reference has a value" if ours is None
                    else "ours has a value, reference errors" if ref is None else "values differ")
            res["fail"].append({"expr": c["text"], "mode": mode, "ours": c["ours"], "ref": ref, "kind": kind})
    return res


# ------------------------------------------------------------------ 2. derivatives
def check_derivatives(cases):
    strict, cplx = strict_env(), complex_env()
    h = 1e-30
    res = {"n": 0, "pass": 0, "skipped": 0, "rel_errors": [], "fail": [], "points": 0,
           "printed_pass": 0, "printed_errors": []}
    for c in cases:
        points = []  # (x, reference derivative, our value, our value from the printed text)
        n_pts = len(c["xs"])
        for x, ours, printed in zip(c["xs"], c["values"] or [None] * n_pts, c["printedValues"] or [None] * n_pts):
            try:
                v = evaluate(c["py"], strict, x)
                if isinstance(v, complex) or not math.isfinite(v):
                    continue
                d = evaluate(c["py"], cplx, complex(x, h)).imag / h
                if not math.isfinite(d):
                    continue
            except (ValueError, ZeroDivisionError, OverflowError):
                continue
            points.append((x, d, ours, printed))
        if not points:
            res["skipped"] += 1
            continue
        res["n"] += 1
        res["points"] += len(points)
        bad = None
        printed_ok = True
        if c["error"] or c["values"] is None:
            bad = f"our code raised: {c['error']}"
            printed_ok = False
        else:
            for x, ref, ours, printed in points:
                if ours is None or not math.isfinite(ours) or not close(ours, ref, 1e-9):
                    bad = f"x={x}: ours={ours}, reference={ref:.15g}"
                    break
                res["rel_errors"].append(abs(ours - ref) / max(1.0, abs(ref)))
                if printed is None or not math.isfinite(printed) or not close(printed, ref, 1e-8):
                    printed_ok = False
                else:
                    res["printed_errors"].append(abs(printed - ref) / max(1.0, abs(ref)))
        if bad:
            res["fail"].append({"expr": c["text"], "result": c["sym"], "why": bad})
        else:
            res["pass"] += 1
            if printed_ok:
                res["printed_pass"] += 1
    return res


# ------------------------------------------------------------------ 3. integrals
NODES, WEIGHTS = np.polynomial.legendre.leggauss(64)


def gauss_legendre(py, lo, hi, env):
    mid, half = (hi + lo) / 2, (hi - lo) / 2
    total = 0.0
    for t, w in zip(NODES, WEIGHTS):
        v = evaluate(py, env, mid + half * float(t))
        if isinstance(v, complex) or not math.isfinite(v):
            raise ValueError("integrand undefined")
        total += float(w) * v
    return half * total


def check_integrals(cases):
    strict = strict_env()
    res = {"n": 0, "simpson_pass": 0, "sym_n": 0, "sym_pass": 0, "in_scope": 0, "in_scope_solved": 0,
           "out_scope": 0, "out_scope_declined": 0, "out_scope_solved_correctly": 0,
           "simpson_err": [], "sym_err": [], "fail": [], "skipped": 0,
           "printed_pass": 0, "printed_errors": []}
    for c in cases:
        try:
            ref = gauss_legendre(c["py"], c["lo"], c["hi"], strict)
        except (ValueError, ZeroDivisionError, OverflowError):
            res["skipped"] += 1
            continue
        res["n"] += 1
        fam = res.setdefault("families", {}).setdefault(
            c.get("family", "unspecified"),
            {"scope": c["scope"], "n": 0, "solved": 0, "correct": 0, "ms": []})
        fam["n"] += 1
        fam["ms"].append(c.get("ms", 0.0))
        if c["scope"] == "in":
            res["in_scope"] += 1
        elif c["scope"] == "out":
            res["out_scope"] += 1
        if c["error"]:
            res["fail"].append({"expr": c["text"], "why": f"our code raised: {c['error']}"})
            continue
        if c["simpson"] is not None and close(c["simpson"], ref, 1e-8):
            res["simpson_pass"] += 1
            res["simpson_err"].append(abs(c["simpson"] - ref) / max(1.0, abs(ref)))
        else:
            res["fail"].append({"expr": c["text"], "why": f"Simpson ours={c['simpson']}, reference={ref:.15g}"})
        if c["sym"] is None:
            if c["scope"] == "out":
                res["out_scope_declined"] += 1
            continue
        res["sym_n"] += 1
        fam["solved"] += 1
        if c["scope"] == "in":
            res["in_scope_solved"] += 1
        if c["fromF"] is not None and close(c["fromF"], ref, 1e-9):
            res["sym_pass"] += 1
            fam["correct"] += 1
            res["sym_err"].append(abs(c["fromF"] - ref) / max(1.0, abs(ref)))
            if c["scope"] == "out":
                res["out_scope_solved_correctly"] += 1
            if c["fromFPrinted"] is not None and close(c["fromFPrinted"], ref, 1e-8):
                res["printed_pass"] += 1
                res["printed_errors"].append(abs(c["fromFPrinted"] - ref) / max(1.0, abs(ref)))
        else:
            res["fail"].append({"expr": c["text"], "why": f"F(b)-F(a) ours={c['fromF']}, reference={ref:.15g}, F={c['sym']}"})
    return res


# ------------------------------------------------------------------ report
def pct(a, b):
    return "n/a" if b == 0 else f"{100 * a / b:.2f}%"


def ci(a, b):
    lo, hi = wilson(a, b)
    return f"[{100 * lo:.2f}%, {100 * hi:.2f}%]"


def stats(errs):
    if not errs:
        return "n/a", "n/a"
    return f"{statistics.median(errs):.1e}", f"{max(errs):.1e}"


def table_rows(failures, cols, limit=12):
    lines = []
    for f in failures[:limit]:
        lines.append("| " + " | ".join(str(f[c]).replace("|", "\\|")[:90] for c in cols) + " |")
    if len(failures) > limit:
        lines.append(f"| ... {len(failures) - limit} more | | | |"[: 1000])
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-pass", type=float, default=0.0, help="exit 1 if any category pass rate is lower")
    args = ap.parse_args()

    with open(os.environ.get("QL_CASES") or os.path.join(HERE, "cases.json"), encoding="utf-8") as f:
        data = json.load(f)

    arith = check_arithmetic(data["arithmetic"])
    deriv = check_derivatives(data["derivative"])
    integ = check_integrals(data["integral"])

    a_med, a_max = stats(arith["rel_errors"])
    d_med, d_max = stats(deriv["rel_errors"])
    s_med, s_max = stats(integ["simpson_err"])
    f_med, f_max = stats(integ["sym_err"])
    dp_med, dp_max = stats(deriv["printed_errors"])
    ip_med, ip_max = stats(integ["printed_errors"])

    L = []
    L.append("# Validation report")
    L.append("")
    L.append(f"Generated by `npm run validate` (seed `{data['seed']}`). Reproduce exactly with the same seed.")
    L.append("")
    L.append("**What is compared.** Each case is a random expression tree rendered twice: in the calculator's own syntax "
             "(evaluated by `calculator.js` / `calculus.js`) and in Python syntax (evaluated here with `math`, `cmath` and numpy). "
             "A mismatch is a bug in one of the two evaluators. 95% intervals are Wilson score intervals.")
    L.append("")
    L.append("| Area | Cases | Passed | Pass rate | 95% CI | Median rel. error | Max rel. error |")
    L.append("|---|---|---|---|---|---|---|")
    L.append(f"| Arithmetic and functions | {arith['n']} | {arith['pass']} | {pct(arith['pass'], arith['n'])} | {ci(arith['pass'], arith['n'])} | {a_med} | {a_max} |")
    L.append(f"| Derivatives (symbolic, checked at {deriv['points']} points) | {deriv['n']} | {deriv['pass']} | {pct(deriv['pass'], deriv['n'])} | {ci(deriv['pass'], deriv['n'])} | {d_med} | {d_max} |")
    L.append(f"| Definite integrals, Simpson (n=1000) | {integ['n']} | {integ['simpson_pass']} | {pct(integ['simpson_pass'], integ['n'])} | {ci(integ['simpson_pass'], integ['n'])} | {s_med} | {s_max} |")
    L.append(f"| Antiderivatives returned, F(b)-F(a) | {integ['sym_n']} | {integ['sym_pass']} | {pct(integ['sym_pass'], integ['sym_n'])} | {ci(integ['sym_pass'], integ['sym_n'])} | {f_med} | {f_max} |")
    L.append("")
    L.append("Copy-paste fidelity: the same results, but re-evaluated from the printed 12-digit text a user would copy.")
    L.append("")
    L.append("| Printed result | Cases | Reproduces value | Pass rate | 95% CI | Median rel. error | Max rel. error |")
    L.append("|---|---|---|---|---|---|---|")
    L.append(f"| Derivative text | {deriv['pass']} | {deriv['printed_pass']} | {pct(deriv['printed_pass'], deriv['pass'])} | {ci(deriv['printed_pass'], deriv['pass'])} | {dp_med} | {dp_max} |")
    L.append(f"| Antiderivative text | {integ['sym_pass']} | {integ['printed_pass']} | {pct(integ['printed_pass'], integ['sym_pass'])} | {ci(integ['printed_pass'], integ['sym_pass'])} | {ip_med} | {ip_max} |")
    L.append("")
    L.append("Pass tolerance: relative error <= 1e-9 (1e-8 for Simpson and for printed text) with an absolute floor of the same size.")
    L.append("")
    L.append("## Arithmetic detail")
    L.append("")
    L.append(f"- Excluded as ill-conditioned (`mod` with a quotient above 1e9, so the answer depends on bits below double precision): {arith['excluded']}.")
    L.append(f"- Cases where both evaluators correctly reported an error (division by zero, domain errors, overflow): {arith['both_error']}.")
    for k, (p, n) in arith["by_kind"].items():
        L.append(f"- {k}: {p}/{n} ({pct(p, n)})")
    for k, (p, n) in arith["by_mode"].items():
        L.append(f"- {k} mode: {p}/{n} ({pct(p, n)})")
    L.append("")
    L.append("*Precedence chains* are flat, unparenthesised inputs (`2^3^2`, `-2^2`, `8/2/2`) whose reference is Python's own parser. "
             "*Special angles and edge values* are exact multiples of 15°/(π/2), inverse-trig endpoints, domain errors, factorial limits and overflow.")
    L.append("")
    L.append("## Scope and coverage (integration)")
    L.append("")
    L.append(f"- Integrands built from the supported rule families: {integ['in_scope']}; closed form found for "
             f"{integ['in_scope_solved']} ({pct(integ['in_scope_solved'], integ['in_scope'])}).")
    L.append(f"- Integrands deliberately outside the rules (e.g. x*sin(x), exp(x^2)): {integ['out_scope']}; "
             f"correctly declined (\"no closed form\") for {integ['out_scope_declined']}, "
             f"returned a verified-correct antiderivative for {integ['out_scope_solved_correctly']}.")
    L.append(f"- Cases skipped because the reference itself was undefined on the interval: derivative {deriv['skipped']}, integral {integ['skipped']}.")
    L.append("")
    L.append("### Integration by method")
    L.append("")
    L.append("Every returned antiderivative is checked by the app itself (its derivative must reproduce the integrand) before it is shown, "
             "so a faulty rule appears here as lower **coverage**, not as a wrong answer. *Correct* is judged independently against Gauss-Legendre quadrature.")
    L.append("")
    L.append("| Method / family | Cases | Closed form found | Coverage | Found and correct | Median time | Slowest |")
    L.append("|---|---|---|---|---|---|---|")
    for name, f in integ.get("families", {}).items():
        ms = sorted(f["ms"])
        med = ms[len(ms) // 2] if ms else 0.0
        if f["scope"] == "in":
            cov = pct(f["solved"], f["n"])
            found = f"{f['solved']}"
        elif f["scope"] == "mixed":
            cov = f"{pct(f['solved'], f['n'])} (informational)"
            found = f"{f['solved']}"
        else:
            cov = f"declined {f['n'] - f['solved']}/{f['n']}"
            found = f"{f['solved']} (must be verified correct)"
        L.append(f"| {name} | {f['n']} | {found} | {cov} | {f['correct']}/{f['solved']} | {med:.1f} ms | {ms[-1] if ms else 0:.0f} ms |")
    L.append("")
    if arith["fail"]:
        L.append("## Arithmetic failures")
        L.append("")
        L.append("| Expression | Mode | Ours | Reference | Kind |")
        L.append("|---|---|---|---|---|")
        L += table_rows(arith["fail"], ["expr", "mode", "ours", "ref", "kind"])
        L.append("")
    if deriv["fail"]:
        L.append("## Derivative failures")
        L.append("")
        L.append("| Expression | Our derivative | Why |")
        L.append("|---|---|---|")
        L += table_rows(deriv["fail"], ["expr", "result", "why"])
        L.append("")
    if integ["fail"]:
        L.append("## Integral failures")
        L.append("")
        L.append("| Expression | Why |")
        L.append("|---|---|")
        L += table_rows(integ["fail"], ["expr", "why"])
        L.append("")
    L.append("## Limits of this validation")
    L.append("")
    L.append("- The reference shares the expression *tree* with the generator, so tree-generation bugs are not caught, only evaluator bugs.")
    L.append("- Derivatives and integrals are checked numerically at sampled points, not proven equal symbolically.")
    L.append("- Random trees are not a substitute for real student input; see `docs/USABILITY_TEST.md`.")
    L.append("")

    report_path = os.environ.get("QL_REPORT") or os.path.join(HERE, "REPORT.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))

    rates = {
        "arithmetic": arith["pass"] / max(1, arith["n"]),
        "derivative": deriv["pass"] / max(1, deriv["n"]),
        "simpson": integ["simpson_pass"] / max(1, integ["n"]),
        "antiderivative": integ["sym_pass"] / max(1, integ["sym_n"]),
        "coverage": integ["in_scope_solved"] / max(1, integ["in_scope"]),
        "textbook": (lambda f: f["solved"] / max(1, f["n"]))(
            next((f for k, f in integ.get("families", {}).items() if k.startswith("textbook")), {"solved": 0, "n": 0})),
        "printed_deriv": deriv["printed_pass"] / max(1, deriv["pass"]),
        "printed_anti": integ["printed_pass"] / max(1, integ["sym_pass"]),
    }
    for k, v in rates.items():
        print(f"{k:15s} {100 * v:6.2f}%")
    print("report:", os.path.relpath(report_path))
    # "textbook" is informational (hand-picked problems, some beyond the methods): shown, never gating.
    if any(v < args.min_pass for k, v in rates.items() if k != "textbook"):
        sys.exit(1)


if __name__ == "__main__":
    main()
